/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Sun Jun 01 01:18:06 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


